services:

  pv111.redis:
    container_name: pv111.redis
    image: redis
    ports:
      - "6379:6379"

  pv111.rabbit.mq:
    container_name: pv111.rabbit.mq
    image: rabbitmq:3.12.0-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER:user
      - RABBITMQ_DEFAULT_PASS:password
    ports:
      - "5672:5672"
      - "15672:15672"

  pv111.storage.minio:
    container_name: pv111.storage.minio
    image: minio/minio:latest
    command: server --console-address :9001 /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./volumes/minio:/data
    expose:
      - "9000"
      - "9001"
    environment:
       MINIO_ROOT_USER: user
       MINIO_ROOT_PASSWORD: password

  mysql:
    container_name: java.pv111.mysql
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=pv111'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=QweAsdZxc!23'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'
