FROM openjdk:21

WORKDIR /app

# Скопируем скомпилированный код в контейнер
COPY ./target /app

# /app/classes/com/itstep/first_spring/FirstSpringApplication
# CMD ["java", "/app/classes/com/itstep/first_spring/FirstSpringApplication"]
# CMD ["java", "com.itstep.first_spring.FirstSpringApplication"]